### ISSUE TITLE
[Feature request] Add action typing

### ISSUE THREAD

**Issue by krzema12** [madhead/read-java-properties#36]
Hi @madhead!

Maintainer of https://github.com/krzema12/github-actions-kotlin-dsl here. Your 3 actions have first-class support in the library.

Recently we've come up with a way to reduce operational load when keeping library's action wrappers in sync with actions' inputs. The solution includes onboarding https://github.com/krzema12/github-actions-typing. It's as easy as adding an extra YAML file to your repository root, and adding a simple GitHub workflow that validates this new file. Thanks to this, the code generator in the Kotlin DSL can fetch typing info provided by you instead of us, which has a number of benefits. It has no negative effects on current action consumers, they continue to use the action via regular GitHub API, as if the file wasn't there.

In this feature request, I would like to ask you if you're open to introducing such typings in your actions. You wouldn't be first - there's already another action using it: https://github.com/Vampire/setup-wsl

If your answer is "yes", feel free to either add it yourself, or let me know - me or some of my fellow contributors would be happy to post PRs. We're also open to any kind of questions and feedback.

**Comment by madhead** [comment]
Hi, @krzema12!

Thanks for the update. Please, check these PRs where I've added the typings:

- https://github.com/madhead/check-gradle-version/pull/503
- https://github.com/madhead/read-java-properties/pull/37
- https://github.com/madhead/semver-utils/pull/438

Are they ok?

**Comment by krzema12** [comment]
Yes, they all look fine, thanks a lot! Looking forward to releases, then I'll switch our library/DSL to consume your action-types.yml.

**Comment by krzema12** [comment]
@madhead it would be great if you could advance the major version tags so that they point to commits with the typings. See e. g. this version: https://github.com/madhead/check-gradle-version/releases/tag/v1 - it still points to a commit from 2020.

https://github.com/actions/toolkit/blob/main/docs/action-versioning.md
(see Recommendations in particular)

**Comment by madhead** [comment]
@krzema12, I've re-pushed the `v1` tag for `madhead/check-gradle-version` to the latest `main` tip. Is it ok now?

**Comment by krzema12** [comment]
Yes, they all look fine now. Now I'm leaving for vacation, but after that I'll make necessary adjustments in our code generation module - this will be the ultimate confirmation if everything's fine. For now, let's leave it as resolved 😄 thanks!

**Comment by madhead** [comment]
Thank you! Have a nice and refreshing vacation!
