### ISSUE TITLE
The `set-output` command is deprecated and will be disabled soon.

### ISSUE THREAD

**Issue by RedLime** [madhead/read-java-properties#39]
thanks for this package, but there is minor issue,

when I run workflow, it said like this.
`Warning: The 'set-output' command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/`

It's not very important, but if not fixed it will stop working in May 2023.

**Comment by madhead** [comment]
Hi, @RedLime!

Thank you for highlighting this! I've released `2.0.0` version of this action, please try it.
