### ISSUE TITLE
Support reading values containing line separators

### ISSUE THREAD

**Issue by Fallen-Breath** [madhead/read-java-properties#64]
If the properties files contains value containing line separators, e.g.:

```properties
abc=123
foo=bar\nbaz
```

The github action will fail, since the content format of the `GITHUB_OUTPUT` file cannot be recognized by the workflow

GITHUB_OUTPUT output with the current inplementation:

```
abc=123
foo=bar
baz
```

Expected GITHUB_OUTPUT  output (using the method from https://github.com/github/docs/issues/21529):

```
abc=123
foo<<DELIMITER
bar
baz
DELIMITER
```

Example implentation, just for a reference

```kotlin
fun packKeyValue(key: Any, value: Any): String {
    val s = value.toString()
    if (s.contains('\n') || s.contains('\r')) {
        var delimiter = "VALUE_DELIMITER"
        while (s.contains(delimiter)) {
            delimiter += "_X"
        }
        return "$key<<$delimiter${lineSeparator()}$s${lineSeparator()}$delimiter"
    } else {
        return "$key=$value"
    }
}
```

**Comment by madhead** [comment]
Hey, @Fallen-Breath, thanks for reporting! Could you please try the latest version (4.0.0)?
